name: label sync


on:
  push:
    branches:
      - master
    paths:
      - '.github/labels.yml'
      - '.github/workflows/label-sync.yml'

jobs:
  label-sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: label sync
        if: success()
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
