name: Renovate Validate

on: pull_request


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn
    - name: Run validate
      run: yarn test
