name: Renovate Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: yarn
    - name: Run validate
      run: yarn test